import { type Plugins } from '@pdfme/common';
import {
  barcodes,
  checkbox,
  date,
  dateTime,
  ellipse,
  image,
  line,
  multiVariableText,
  radioGroup,
  rectangle,
  select,
  svg,
  table,
  text,
  time,
} from '@pdfme/schemas';

import { signature } from './signature';

export default {
  Checkbox: checkbox,
  Code39: barcodes.code39,
  Code128: barcodes.code128,
  Date: date,
  DateTime: dateTime,
  EAN8: barcodes.ean8,
  EAN13: barcodes.ean13,
  Ellipse: ellipse,
  GS1DataMatrix: barcodes.gs1datamatrix,
  Image: image,
  ITF14: barcodes.itf14,
  JAPANPOST: barcodes.japanpost,
  Line: line,
  'Multi-Variable Text': multiVariableText,
  NW7: barcodes.nw7,
  PDF417: barcodes.pdf417,
  QR: barcodes.qrcode,
  RadioGroup: radioGroup,
  Rectangle: rectangle,
  Select: select,
  Signature: signature,
  SVG: svg,
  Table: table,
  Text: text,
  Time: time,
  UPCA: barcodes.upca,
  UPCE: barcodes.upce,
} as Plugins;
