name: Mobile Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to build for
        required: true
        type: choice
        options:
          - production
          - preview
  workflow_call:
    inputs:
      environment:
        description: Environment to build for
        required: true
        type: string

defaults:
  run:
    working-directory: 'apps/mobile'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ios
            name: iOS
            os: macos-latest
    #          - platform: android
    #            name: Android
    #            os: ubuntu-latest

    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    environment: ${{ inputs.environment }}
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm add --global eas-cli
      - run: eas build --non-interactive --auto-submit --platform ${{ matrix.platform }} --profile ${{ inputs.environment }}

  push-update:
    name: Push Update
    runs-on: macos-latest
    environment: ${{ inputs.environment }}
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm add --global eas-cli
      - run: eas env:pull --non-interactive --environment ${{ inputs.environment }}
      - run: turbo build:update -- --environment ${{ inputs.environment }}
      - run: dotenvx run -f .env.local -- pnpx sentry-expo-upload-sourcemaps dist
