name: Mobile Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to build for
        required: true
        type: choice
        options:
          - production
          - preview

  workflow_call:
    inputs:
      environment:
        description: Environment to build for
        required: true
        type: string

concurrency:
  group: ${{ inputs.environment }}-mobile-deploy

defaults:
  run:
    working-directory: 'apps/mobile'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ios
            name: iOS
            os: macos-latest
    #          - platform: android
    #            name: Android
    #            os: ubuntu-latest

    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    environment: ${{ inputs.environment }}
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm add --global eas-cli

      - uses: actions/cache@v4
        with:
          path: eas-fingerprint.txt
          key: eas-fingerprint-${{ matrix.platform }}-${{ inputs.environment }}

      - name: Compare fingerprints
        id: fingerprint
        run: |
          if [ ! -f eas-fingerprint.txt ]; then
            echo "Previous fingerprint not found, native build needed"
            echo "build-needed=true" >> $GITHUB_OUTPUT
          elif eas fingerprint:compare $(cat eas-fingerprint.txt) --platform ${{ matrix.platform }} --environment ${{ inputs.environment }}; then
            echo "Fingerprint unchanged, no native build needed"
            echo "build-needed=false" >> $GITHUB_OUTPUT
          else
            echo "Fingerprint changed, native build needed"
            echo "build-needed=true" >> $GITHUB_OUTPUT
          fi

      - name: Native Build
        if: steps.fingerprint.outputs.build-needed == 'true'
        run: eas build --non-interactive --json --platform ${{ matrix.platform }} --profile ${{ inputs.environment }} | jq -r '.[0].runtimeVersion' > eas-fingerprint.txt

      - name: EAS Update
        if: steps.fingerprint.outputs.build-needed == 'false'
        run: |
          eas update --non-interactive --json --platform ${{ matrix.platform }} --channel ${{ inputs.environment }} --environment ${{ inputs.environment }} --message ${{ github.sha }} | jq -r '.[0].runtimeVersion' > eas-fingerprint.txt
          eas env:pull --non-interactive --environment ${{ inputs.environment }}
          dotenvx run -f .env.local -- pnpx sentry-expo-upload-sourcemaps dist
